/* =========================================================
   产品数据（可编辑）
   目标：零基础也能新增产品（不需要懂 JS，只照着改）

   【怎么新增产品】
   1) 复制下面任意一个 product 对象（从 { 到 } 这一整段）
   2) 改 id（只能用英文/数字/短横线），改 category、name、images、specs、points
   3) 在 products 数组里粘贴即可

   【图片怎么换】
   - 直接改 images 里的链接即可
   - 你可以用本站相对路径（例如 assets/img/extracted/tractor-1.png）
   - 也可以用在线 URL（例如 https://.../tractor.jpg）
   ========================================================= */

window.PRODUCT_CATEGORIES = [
  { key: "tractors", icon: "🚜" },
  { key: "seeders", icon: "🌱" },
  { key: "irrigation", icon: "💧" },
  { key: "construction", icon: "🏗️" },
  { key: "spare_parts", icon: "⚙️" },
];

// 可编辑：分类名称（多语言）
window.CATEGORY_NAMES = {
  en: { tractors: "Agricultural Tractors", seeders: "Seeders & Implements", irrigation: "Smart Irrigation", construction: "Construction Machinery", spare_parts: "Machinery Spare Parts" },
  fr: { tractors: "Tracteurs agricoles", seeders: "Semoirs & outils", irrigation: "Irrigation intelligente", construction: "Engins de chantier", spare_parts: "Pièces détachées" },
  es: { tractors: "Tractores agrícolas", seeders: "Sembradoras y aperos", irrigation: "Riego inteligente", construction: "Maquinaria de obra", spare_parts: "Repuestos" },
  ar: { tractors: "جرارات زراعية", seeders: "بذارات وملحقات", irrigation: "ري ذكي", construction: "معدات إنشائية", spare_parts: "قطع غيار" },
  ru: { tractors: "Сельхозтракторы", seeders: "Сеялки и навесное", irrigation: "Умный полив", construction: "Строительная техника", spare_parts: "Запчасти" },
  pt: { tractors: "Tratores agrícolas", seeders: "Semeadoras & implementos", irrigation: "Irrigação inteligente", construction: "Máquinas de construção", spare_parts: "Peças" },
};

// =========================================================
// 可编辑：产品列表（从附件 PDF 提取并整理，仍可继续补充/修改）
// =========================================================
window.PRODUCTS = [
  {
    id: "tts350-series",
    category: "tractors",
    images: [
      "assets/img/extracted/tractor-hero.png",
      "assets/img/extracted/tractor-1.png",
      "assets/img/extracted/tractor-2.png",
    ],
    name: {
      en: "TTS350/354/400/404 Tractor Series",
      fr: "Série de tracteurs TTS350/354/400/404",
      es: "Serie de tractores TTS350/354/400/404",
      ar: "سلسلة الجرارات TTS350/354/400/404",
      ru: "Серия тракторов TTS350/354/400/404",
      pt: "Série de tratores TTS350/354/400/404",
    },
    short: {
      en: "Compact tractors for mixed farming, orchard and small-to-medium field work.",
      fr: "Tracteurs compacts pour polyculture, vergers et petites/moyennes exploitations.",
      es: "Tractores compactos para agricultura mixta, huertos y campos pequeños/medianos.",
      ar: "جرارات مدمجة للزراعة المتنوعة والبساتين والأعمال الحقلية.",
      ru: "Компактные тракторы для смешанного сельского хозяйства и садов.",
      pt: "Tratores compactos para agricultura mista, pomares e campos pequenos/médios.",
    },
    points: {
      en: [
        "Efficient operation: 8+2 gearbox, optional 10+2 for better speed matching.",
        "Hydraulic power steering for light and precise control.",
        "High ground clearance and adjustable rear wheel tread for wider application.",
        "Optional narrow tread (960mm) for greenhouse / orchard operations.",
      ],
      fr: [
        "Efficacité: boîte 8+2, option 10+2 pour une meilleure adaptation de vitesse.",
        "Direction assistée hydraulique, conduite souple.",
        "Garde au sol élevée + voie arrière réglable, usage polyvalent.",
        "Option voie étroite (960mm) pour vergers/serres.",
      ],
      es: [
        "Operación eficiente: caja 8+2, opcional 10+2 para mejor ajuste de velocidad.",
        "Dirección asistida hidráulica, control ligero.",
        "Alta distancia al suelo y vía trasera ajustable para más aplicaciones.",
        "Opción de vía estrecha (960mm) para invernaderos/huertos.",
      ],
      ar: [
        "تشغيل عالي الكفاءة: ناقل 8+2 مع خيار 10+2 لتوافق السرعات.",
        "توجيه هيدروليكي لسهولة التحكم.",
        "خلوص أرضي مرتفع ومسار خلفي قابل للتعديل.",
        "خيار مسار ضيق (960 مم) للبيوت المحمية والبساتين.",
      ],
      ru: [
        "Эффективная работа: КПП 8+2, опция 10+2 для оптимальной скорости.",
        "Гидроусилитель руля для лёгкого управления.",
        "Высокий клиренс и регулируемая задняя колея.",
        "Опция узкой колеи (960 мм) для садов/теплиц.",
      ],
      pt: [
        "Operação eficiente: câmbio 8+2, opcional 10+2 para melhor combinação de velocidades.",
        "Direção hidráulica para controle leve.",
        "Alta folga do solo e bitola traseira ajustável.",
        "Opção de bitola estreita (960mm) para estufas/pomares.",
      ],
    },
    specs: {
      // 可编辑：只改右侧的值（结构固定）
      modelRange: "TTS350 / TTS354 / TTS400 / TTS404",
      dimensions: "Length 3125–3300 mm; Width 1410–1510 mm; Height 2025–2100 mm (series range)",
      enginePower: "25.8–29.5 kW",
      pto: "540/750; 540/1000; 750/1000 (options)",
      frontTread: "1123/1175/1127/1215 mm (adjustable by model)",
      rearTread: "1104–1205 mm (adjustable)",
      traction: "7.5–12 kN (by model)",
      minWeight: "≥ 578–660 kg (by model)",
      transmission: "8+2 standard; 10+2 optional",
      steering: "Hydraulic power steering",
      warranty: "12 months or 1000 working hours",
      notes: "Engine options: Laidong / Xichai / Changchai (subject to configuration).",
    },
  },

  {
    id: "tts450-series",
    category: "tractors",
    images: ["assets/img/extracted/tractor-1.png", "assets/img/extracted/tractor-2.png"],
    name: {
      en: "TTS450/454/500/504 Tractor Series",
      fr: "Série de tracteurs TTS450/454/500/504",
      es: "Serie de tractores TTS450/454/500/504",
      ar: "سلسلة الجرارات TTS450/454/500/504",
      ru: "Серия тракторов TTS450/454/500/504",
      pt: "Série de tratores TTS450/454/500/504",
    },
    short: {
      en: "Mid-range tractors designed for tougher tillage and higher daily workload.",
      fr: "Tracteurs milieu de gamme pour un travail plus intensif.",
      es: "Tractores de gama media para trabajo más exigente.",
      ar: "جرارات متوسطة للأعمال الشاقة وزيادة الإنتاجية.",
      ru: "Средний класс для более тяжёлых работ.",
      pt: "Tratores de médio porte para trabalho mais pesado.",
    },
    points: {
      en: [
        "8+2 transmission, optional 10+2.",
        "Optional dual-stage clutch to improve PTO operation efficiency.",
        "Hydraulic steering, stable chassis and good passability.",
        "Optional multi-channel hydraulic output for different implements.",
      ],
      fr: [
        "Transmission 8+2, option 10+2.",
        "Embrayage double effet en option pour améliorer l’utilisation PDF.",
        "Direction hydraulique, châssis stable.",
        "Sorties hydrauliques multiples en option.",
      ],
      es: [
        "Transmisión 8+2, opcional 10+2.",
        "Embrague de dos etapas opcional para mejorar la PTO.",
        "Dirección hidráulica y chasis estable.",
        "Salidas hidráulicas múltiples opcionales.",
      ],
      ar: [
        "ناقل 8+2 مع خيار 10+2.",
        "قابض مزدوج (اختياري) لتحسين تشغيل PTO.",
        "توجيه هيدروليكي وهيكل ثابت.",
        "مخارج هيدروليكية متعددة (اختياري).",
      ],
      ru: [
        "КПП 8+2, опция 10+2.",
        "Опция двухступенчатого сцепления для ВОМ.",
        "Гидроусилитель и стабильная рама.",
        "Опция многоканальной гидравлики под навесное.",
      ],
      pt: [
        "Transmissão 8+2, opcional 10+2.",
        "Embreagem dupla opcional para melhor operação do PTO.",
        "Direção hidráulica e chassi estável.",
        "Saídas hidráulicas múltiplas opcionais.",
      ],
    },
    specs: {
      modelRange: "TTS450 / TTS454 / TTS500 / TTS504",
      dimensions: "Length 3230–3370 mm; Width 1490–1495 mm; Height 2360 mm",
      enginePower: "33.1–36.8 kW",
      pto: "540/750; 540/1000; 750/1000 (options)",
      frontTread: "1200–1250 mm (adjustable by model)",
      rearTread: "1200 mm (adjustable)",
      traction: "8.3–9.2 kN (by model)",
      minWeight: "≥ 740–850 kg (by model)",
      transmission: "8+2 standard; 10+2 optional",
      steering: "Hydraulic power steering",
      warranty: "12 months or 1000 working hours",
      notes: "Engine options: Laidong / Xichai (subject to configuration).",
    },
  },

  {
    id: "portable-seeder-frvps",
    category: "seeders",
    images: ["assets/img/extracted/seeder-hero.png", "assets/img/extracted/seeder-1.png"],
    name: {
      en: "Portable Seeder (Hand-held)",
      fr: "Semoir portable (manuel)",
      es: "Sembradora portátil (manual)",
      ar: "بذّارة محمولة (يدوية)",
      ru: "Портативная сеялка (ручная)",
      pt: "Semeadora portátil (manual)",
    },
    short: {
      en: "Lightweight seeder for small plots, greenhouse and orchard inter-row sowing.",
      fr: "Semoir léger pour petites parcelles, serres et vergers.",
      es: "Sembradora ligera para parcelas pequeñas, invernadero y huertos.",
      ar: "بذّارة خفيفة للقطع الصغيرة والبيوت المحمية والبساتين.",
      ru: "Лёгкая сеялка для небольших участков, теплиц и садов.",
      pt: "Semeadora leve para pequenas áreas, estufas e pomares.",
    },
    points: {
      en: [
        "Portable and easy to operate for quick sowing jobs.",
        "Multiple model options (weight and loading) for different applications.",
        "Ideal for distributors targeting small-farm and retail channels.",
      ],
      fr: [
        "Portable et simple d’utilisation pour semis rapides.",
        "Plusieurs modèles (poids / chargement) selon besoins.",
        "Idéal pour les canaux retail et petites fermes.",
      ],
      es: [
        "Portátil y fácil de usar para siembras rápidas.",
        "Varias opciones de modelo (peso/carga).",
        "Ideal para canales minoristas y pequeñas granjas.",
      ],
      ar: [
        "محمولة وسهلة التشغيل للزراعة السريعة.",
        "خيارات موديلات متعددة حسب الوزن/التعبئة.",
        "مناسبة لقنوات التجزئة والمزارع الصغيرة.",
      ],
      ru: [
        "Портативная и простая в работе.",
        "Несколько моделей по весу и упаковке.",
        "Подходит для розницы и малых хозяйств.",
      ],
      pt: [
        "Portátil e fácil de operar para semeadura rápida.",
        "Várias opções de modelo (peso/embalagem).",
        "Ideal para varejo e pequenas fazendas.",
      ],
    },
    specs: {
      modelRange: "FR-VPS / FR-HHN / FR-HHD (example series)",
      dimensions: "150×150×820 mm; 200×140×820 mm (by model)",
      enginePower: "Manual",
      pto: "N/A",
      frontTread: "N/A",
      rearTread: "N/A",
      traction: "N/A",
      minWeight: "1.5–2.6 kg (by model)",
      transmission: "N/A",
      steering: "N/A",
      warranty: "12 months (support available)",
      notes: "Parameters can be updated based on your exact model and packaging requirement.",
    },
  },

  {
    id: "smart-drip-kit",
    category: "irrigation",
    images: ["assets/img/extracted/factory-1.png"],
    name: {
      en: "Smart Drip Irrigation System (Project Kit)",
      fr: "Système d'irrigation goutte-à-goutte intelligent",
      es: "Sistema de riego por goteo inteligente",
      ar: "نظام ري بالتنقيط ذكي",
      ru: "Умная система капельного полива",
      pt: "Sistema de irrigação por gotejamento inteligente",
    },
    short: {
      en: "Turnkey solution for farms and agricultural projects: pipes, fittings, filtration, pump and control.",
      fr: "Solution clé en main : tuyaux, raccords, filtration, pompe et contrôle.",
      es: "Solución llave en mano: tuberías, conexiones, filtración, bomba y control.",
      ar: "حل متكامل: أنابيب ووصلات وفلترة ومضخة وتحكم.",
      ru: "Комплект под проект: трубы, фитинги, фильтрация, насос и управление.",
      pt: "Solução turnkey: tubos, conexões, filtragem, bomba e controle.",
    },
    points: {
      en: ["Save water and labor with precise delivery.", "Flexible design for orchard, greenhouse and field.", "Support for BOM, packing and project documentation."],
      fr: ["Économie d’eau et de main-d’œuvre.", "Conception flexible pour verger/serre/champ.", "Support BOM, packing et documents projet."],
      es: ["Ahorro de agua y mano de obra.", "Diseño flexible para huerto/invernadero/campo.", "Soporte de BOM, embalaje y documentos."],
      ar: ["توفير الماء والعمالة.", "تصميم مرن للبساتين والبيوت المحمية والحقول.", "دعم قوائم المواد والتعبئة والمستندات."],
      ru: ["Экономия воды и труда.", "Гибкий дизайн под разные сценарии.", "Помощь с BOM, упаковкой и документацией."],
      pt: ["Economia de água e mão de obra.", "Projeto flexível para vários cenários.", "Suporte a BOM, embalagem e documentos."],
    },
    specs: {
      modelRange: "Custom design (project-based)",
      dimensions: "By project",
      enginePower: "Pump: optional (diesel/electric)",
      pto: "N/A",
      frontTread: "N/A",
      rearTread: "N/A",
      traction: "N/A",
      minWeight: "N/A",
      transmission: "N/A",
      steering: "N/A",
      warranty: "12 months",
      notes: "Replace these placeholders with your confirmed pipe diameter, emitter spacing and working pressure.",
    },
  },

  // =========================================================
  // 农机具（来自 product catalog 图片，可继续补充/校对）
  // 说明：农机具/工程机械用 specPairs 自定义参数表字段（英文）
  // =========================================================
  {
    id: "disc-plough-series",
    category: "seeders",
    images: ["assets/img/extracted/catalog-05.jpg"],
    name: { en: "Disc Plough (Series)" },
    short: { en: "Disc plough series for primary tillage, stable penetration and efficient soil turning." },
    points: {
      en: [
        "Suitable for hard soil conditions and residue coverage; stable working depth.",
        "Multiple disc sizes and disc counts for different tractor horsepower.",
        "Strong frame and easy maintenance for distributors and rental fleets.",
      ],
    },
    specPairs: [
      { label: "Models (examples)", value: "1LYT-225 / 1LYT-325 / 1LYT-425 / 1LYT-525 / 1LYT-625 / 1LYT-725 (and more)" },
      { label: "Working Width", value: "500–1750 mm (by model)" },
      { label: "No. of Discs", value: "2–7 pcs (by model)" },
      { label: "Disc Diameter", value: "350–700 mm (by model)" },
      { label: "Weight", value: "≈ 135–1150 kg (by model)" },
      { label: "Matched Power", value: "≈ 35–220 hp (by model)" },
      { label: "Linkage", value: "3-point mounted (typical)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-05.jpg" },
    ],
  },
  {
    id: "disc-harrow-series",
    category: "seeders",
    images: ["assets/img/extracted/catalog-06.jpg"],
    name: { en: "Disc Harrow (Mounted / Offset / Middle-duty)" },
    short: { en: "Disc harrow series for soil preparation: residue mixing, leveling and seedbed finishing." },
    points: {
      en: [
        "Multiple types: offset heavy-duty, mounted light-duty, opposed light-duty, middle-duty.",
        "Widely used for farm field prep and after-harvest residue incorporation.",
        "Different disc diameter / spacing options available for local soil conditions.",
      ],
    },
    specPairs: [
      { label: "Types", value: "Offset Heavy-duty / Mounted Light-duty / Opposed Light-duty / Mounted Middle-duty" },
      { label: "Working Width", value: "≈ 1600–4500 mm (by type/model)" },
      { label: "No. of Discs", value: "≈ 12–56 pcs (by type/model)" },
      { label: "Disc Diameter", value: "≈ 510–660 mm (by type/model)" },
      { label: "Matched Power", value: "≈ 25–200+ hp (by type/model)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-06.jpg" },
    ],
  },
  {
    id: "rotary-tiller-series",
    category: "seeders",
    images: ["assets/img/extracted/catalog-08.jpg"],
    name: { en: "Rotary Tiller (Series)" },
    short: { en: "Rotary tiller series for fine seedbed and soil crushing with stable depth control." },
    points: {
      en: [
        "Good soil crushing and leveling for seedbed preparation.",
        "Multiple working widths for 12–120 hp tractors (by model).",
        "Easy parts supply: blades and wearing components available.",
      ],
    },
    specPairs: [
      { label: "Models (examples)", value: "1GQN-80 / 1GQN-100 / 1GQN-120 / 1GQN-140 / 1GQN-160 / 1GQN-180 / 1GQN-200 / 1GQN-220 / 1GQN-250 / 1GQN-300 (by catalog)" },
      { label: "Working Width", value: "800–3000 mm (by model)" },
      { label: "Working Depth", value: "≈ 80–180 mm (by model)" },
      { label: "Blade Qty", value: "≈ 18–78 pcs (by model)" },
      { label: "Matched Power", value: "≈ 12–120 hp (by model)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-08.jpg" },
    ],
  },
  {
    id: "corn-seeder-series",
    category: "seeders",
    images: ["assets/img/extracted/catalog-08.jpg"],
    name: { en: "Corn Seeder (Series)" },
    short: { en: "Corn seeder series for accurate sowing and stable row spacing, suitable for distributors." },
    points: {
      en: [
        "Accurate seed placement and stable row spacing.",
        "Multiple-row options for different farm scales.",
        "Works with common tractor 3-point mounting.",
      ],
    },
    specPairs: [
      { label: "Models (examples)", value: "2BYCF-1 / 2BYCF-2 / 2BYCF-3 / 2BYCF-4 / 2BYCF-5 / 2BYCF-6 (by catalog)" },
      { label: "Rows", value: "1–6 rows (by model)" },
      { label: "Row Spacing", value: "≈ 30–50 cm (by model)" },
      { label: "Matched Power", value: "≈ 12–40 hp (by model)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-08.jpg" },
    ],
  },
  {
    id: "fertilizer-spreader-series",
    category: "seeders",
    images: ["assets/img/extracted/catalog-08.jpg"],
    name: { en: "Fertilizer Spreader (Series)" },
    short: { en: "Fertilizer spreader series for efficient field application; multiple capacity options." },
    points: {
      en: [
        "Works for granular fertilizer and related materials (by configuration).",
        "Easy loading and stable spreading for farm operations.",
        "Suitable for distributors: compact size, easy shipping.",
      ],
    },
    specPairs: [
      { label: "Models (examples)", value: "CR-400 / B-16 / CR-600 / ATV-400 / B-16 (by catalog)" },
      { label: "Working Width", value: "≈ 7–10 m (by model)" },
      { label: "Capacity", value: "≈ 100–600 L (by model)" },
      { label: "Matched Power", value: "≈ 18–35 hp (by model)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-08.jpg" },
    ],
  },
  {
    id: "potato-planter-2cm",
    category: "seeders",
    images: ["assets/img/extracted/catalog-10.jpg"],
    name: { en: "Potato Planter (2CM Series)" },
    short: { en: "Potato planter for efficient seeding, ridging and accurate plant spacing." },
    points: {
      en: [
        "Options for single ridge / double ridge configuration.",
        "Designed for stable row spacing and planting depth consistency.",
        "Suitable for export packing and container loading.",
      ],
    },
    specPairs: [
      { label: "Models", value: "2CM-1 (Single ridge) / 2CM-2 (Double ridge for two lines)" },
      { label: "Row Spacing", value: "500–800 mm (by model)" },
      { label: "Plant Spacing", value: "250–1000 mm (adjustable)" },
      { label: "Matched Power", value: "≈ 20–35 hp / 35–60 hp (by model, per catalog)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-10.jpg" },
    ],
  },
  {
    id: "potato-harvester-4ul",
    category: "seeders",
    images: ["assets/img/extracted/catalog-10.jpg"],
    name: { en: "Potato Harvester (4UL Series)" },
    short: { en: "Potato harvester series for efficient digging and separation with reduced crop damage." },
    points: {
      en: [
        "Designed for stable harvesting and soil separation.",
        "Multiple configurations for different row setup and soil types.",
        "Easy maintenance and distributor-friendly spare parts supply.",
      ],
    },
    specPairs: [
      { label: "Models (examples)", value: "4UL-1A / 4UL-1B / 4UL-2 / 4UL-2/2B (by catalog)" },
      { label: "Working Width", value: "550–800 mm (by model)" },
      { label: "Working Depth", value: "100–250 mm (by model)" },
      { label: "Matched Power", value: "≈ 12–30 hp (by model, per catalog)" },
      { label: "Image Source", value: "assets/img/extracted/catalog-10.jpg" },
    ],
  },

  // =========================================================
  // 工程机械（来自截图参数表，已按型号整理）
  // =========================================================
  {
    id: "ht20-mini-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-mini-ht20-ht35g.jpg"],
    name: { en: "HT20 Mini Excavator" },
    short: { en: "Compact mini excavator for landscaping, utility work and small job sites." },
    points: { en: ["Yanmar engine option.", "Easy transport and tight working radius.", "Suitable for dealers and rental fleets."] },
    specPairs: [
      { label: "Engine Type", value: "Yanmar 3TNV76-PCT" },
      { label: "Power", value: "14.1 kW / 2200 rpm" },
      { label: "Overall Weight", value: "1940 kg" },
      { label: "Bucket Capacity", value: "0.06 m³" },
      { label: "Shipping Length", value: "3590 mm" },
      { label: "Transport Height", value: "2400 mm" },
      { label: "Standard Chassis", value: "1350 mm" },
      { label: "Telescopic Chassis", value: "990 / 1300 mm" },
      { label: "Tail Turning Radius", value: "640 mm" },
      { label: "Min. Ground Clearance", value: "180 mm" },
      { label: "Max Digging Radius", value: "4120 mm" },
      { label: "Max Digging Depth", value: "2300 mm" },
      { label: "Hydraulic Pressure", value: "18.6 MPa" },
      { label: "Hydraulic Flow", value: "56 L/min" },
      { label: "Bucket Digging Force", value: "12 kN" },
      { label: "Stick Digging Force", value: "9 kN" },
      { label: "Travel Speed", value: "2–3 km/h" },
    ],
  },
  {
    id: "ht35g-mini-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-mini-ht20-ht35g.jpg"],
    name: { en: "HT35G Mini Excavator" },
    short: { en: "Mini excavator with higher power and capacity for wider application range." },
    points: { en: ["Yanmar engine option.", "Stronger digging force and larger bucket.", "Good balance for dealer inventory."] },
    specPairs: [
      { label: "Engine Type", value: "Yanmar 3TNV88F-ESSY" },
      { label: "Power", value: "18.2 kW / 2200 rpm" },
      { label: "Overall Weight", value: "3600 kg" },
      { label: "Bucket Capacity", value: "0.12 m³" },
      { label: "Shipping Length", value: "4920 mm" },
      { label: "Transport Height", value: "2550 mm" },
      { label: "Overall Width", value: "1720 mm" },
      { label: "Tail Turning Radius", value: "860 mm" },
      { label: "Min. Ground Clearance", value: "295 mm" },
      { label: "Max Digging Radius", value: "5465 mm" },
      { label: "Max Digging Depth", value: "3105 mm" },
      { label: "Hydraulic Pressure", value: "24.5 MPa" },
      { label: "Hydraulic Flow", value: "88 L/min" },
      { label: "Bucket Digging Force", value: "30.5 kN" },
      { label: "Stick Digging Force", value: "18.5 kN" },
      { label: "Travel Speed", value: "2.2–4.4 km/h" },
    ],
  },
  {
    id: "ht70-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht70-ht90.jpg"],
    name: { en: "HT70 Crawler Excavator" },
    short: { en: "Crawler excavator for earthmoving, construction and project contractors." },
    points: { en: ["Optional Yanmar engine for export markets.", "Stable track chassis.", "Balanced weight and productivity."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3065-T480 (48 kW/2200rpm); Optional Yanmar 4TNV98-ZCSLKC (46.3 kW/2200rpm)" },
      { label: "Overall Weight", value: "6260 kg" },
      { label: "Bucket Capacity", value: "0.23 m³" },
      { label: "Shipping Length", value: "6250 mm" },
      { label: "Transport Height", value: "2635 mm" },
      { label: "Overall Width", value: "2180 mm" },
      { label: "Track Gauge", value: "1560 mm" },
      { label: "Track Width", value: "400 mm" },
      { label: "Min. Ground Clearance", value: "250 mm" },
      { label: "Max Digging Radius", value: "6300 mm" },
      { label: "Max Digging Depth", value: "4050 mm" },
      { label: "Max Unloading Height", value: "4200 mm" },
      { label: "Hydraulic Pressure", value: "26 MPa" },
      { label: "Hydraulic Flow", value: "140 L/min" },
      { label: "Bucket Digging Force", value: "45 kN" },
      { label: "Stick Digging Force", value: "22 kN" },
      { label: "Travel Speed", value: "2.3–4.3 km/h" },
    ],
  },
  {
    id: "ht90-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht70-ht90.jpg"],
    name: { en: "HT90 Crawler Excavator" },
    short: { en: "Higher-capacity crawler excavator for tougher jobs and higher daily workload." },
    points: { en: ["Stronger digging force.", "Wider chassis and larger bucket.", "Good for infrastructure contractors."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3085-T480 (62.5 kW/2200rpm); Optional Yanmar 4TNV98T-ZCSTY (54.3 kW/2200rpm)" },
      { label: "Overall Weight", value: "8340 kg" },
      { label: "Bucket Capacity", value: "0.36 m³" },
      { label: "Shipping Length", value: "6200 mm" },
      { label: "Transport Height", value: "2700 mm" },
      { label: "Overall Width", value: "2580 mm" },
      { label: "Track Gauge", value: "1810 mm" },
      { label: "Track Width", value: "450 mm" },
      { label: "Min. Ground Clearance", value: "380 mm" },
      { label: "Max Digging Radius", value: "6370 mm" },
      { label: "Max Digging Depth", value: "4150 mm" },
      { label: "Max Unloading Height", value: "5250 mm" },
      { label: "Hydraulic Pressure", value: "28 MPa" },
      { label: "Hydraulic Flow", value: "160 L/min" },
      { label: "Bucket Digging Force", value: "55 kN" },
      { label: "Travel Speed", value: "2.3–4.5 km/h" },
    ],
  },
  {
    id: "ht150-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht150-ht230.jpg"],
    name: { en: "HT150 Crawler Excavator" },
    short: { en: "15-ton class crawler excavator for earthmoving and jobsite productivity." },
    points: { en: ["Cummins engine options shown in spec.", "Strong digging force.", "Export-friendly configuration."] },
    specPairs: [
      { label: "Engine Type", value: "B3.9CS4 150C (110 kW/2500rpm) / QSB3.9-C125 (93 kW/2200rpm)" },
      { label: "Overall Weight", value: "15540 kg" },
      { label: "Bucket Capacity", value: "0.6 m³" },
      { label: "Shipping Length", value: "7800 mm" },
      { label: "Transport Height", value: "2900 mm" },
      { label: "Overall Width", value: "2500 mm" },
      { label: "Track Length", value: "3470 mm" },
      { label: "Track Gauge", value: "1960 mm" },
      { label: "Track Width", value: "500 mm" },
      { label: "Min. Ground Clearance", value: "420 mm" },
      { label: "Max Digging Radius", value: "8160 mm" },
      { label: "Max Digging Depth", value: "5500 mm" },
      { label: "Max Unloading Height", value: "6150 mm" },
      { label: "Hydraulic Pressure", value: "32 MPa" },
      { label: "Hydraulic Flow", value: "212.6 L/min (as shown)" },
      { label: "Bucket Digging Force", value: "85 kN" },
      { label: "Travel Speed", value: "2–4 km/h" },
    ],
  },
  {
    id: "ht230-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht150-ht230.jpg"],
    name: { en: "HT230 Crawler Excavator" },
    short: { en: "23-ton class crawler excavator for heavy-duty construction tasks." },
    points: { en: ["Large bucket capacity.", "Higher digging force.", "Suitable for contractors and projects."] },
    specPairs: [
      { label: "Engine Type", value: "B5.9CS4 190C (140 kW/2500rpm) / 6BTA5.9-C180-II (132 kW/2200rpm)" },
      { label: "Overall Weight", value: "23200 kg" },
      { label: "Bucket Capacity", value: "1.0 m³" },
      { label: "Shipping Length", value: "9520 mm" },
      { label: "Transport Height", value: "3050 mm" },
      { label: "Overall Width", value: "2990 mm" },
      { label: "Track Length", value: "4250 mm" },
      { label: "Track Gauge", value: "2400 mm" },
      { label: "Track Width", value: "600 mm" },
      { label: "Min. Ground Clearance", value: "440 mm" },
      { label: "Max Digging Radius", value: "10000 mm" },
      { label: "Max Digging Depth", value: "6585 mm" },
      { label: "Max Unloading Height", value: "7585 mm" },
      { label: "Hydraulic Pressure", value: "32 MPa" },
      { label: "Hydraulic Flow", value: "222.4 L/min (as shown)" },
      { label: "Bucket Digging Force", value: "150 kN" },
      { label: "Travel Speed", value: "2–4 km/h" },
    ],
  },
  {
    id: "ht260-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht260-ht300.jpg"],
    name: { en: "HT260 Crawler Excavator" },
    short: { en: "26-ton class crawler excavator for mining, earthmoving and heavy projects." },
    points: { en: ["Stable 600mm track width.", "High hydraulic flow.", "Strong bucket digging force."] },
    specPairs: [
      { label: "Engine Type", value: "6BTA5.9-C180-II (132 kW/2200rpm)" },
      { label: "Overall Weight", value: "25600 kg" },
      { label: "Bucket Capacity", value: "1.2 m³" },
      { label: "Shipping Length", value: "10280 mm" },
      { label: "Transport Height", value: "3255 mm" },
      { label: "Overall Width", value: "3290 mm" },
      { label: "Track Length", value: "4660 mm" },
      { label: "Track Gauge", value: "2590 mm" },
      { label: "Track Width", value: "600 mm" },
      { label: "Min. Ground Clearance", value: "465 mm" },
      { label: "Max Digging Radius", value: "10200 mm" },
      { label: "Max Digging Depth", value: "6350 mm" },
      { label: "Hydraulic Pressure", value: "32 MPa" },
      { label: "Hydraulic Flow", value: "246 L/min (as shown)" },
      { label: "Bucket Digging Force", value: "175 kN" },
      { label: "Travel Speed", value: "2–4 km/h" },
    ],
  },
  {
    id: "ht300-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht260-ht300.jpg"],
    name: { en: "HT300 Crawler Excavator" },
    short: { en: "30-ton class crawler excavator with higher power and productivity." },
    points: { en: ["Higher hydraulic pressure.", "Bigger bucket and stronger force.", "For large contractors and projects."] },
    specPairs: [
      { label: "Engine Type", value: "6LTAA8.9-C325 II (239 kW/2200rpm)" },
      { label: "Overall Weight", value: "29800 kg" },
      { label: "Bucket Capacity", value: "1.7 m³" },
      { label: "Shipping Length", value: "10520 mm" },
      { label: "Transport Height", value: "3490 mm" },
      { label: "Track Length", value: "4840 mm" },
      { label: "Track Gauge", value: "2590 mm" },
      { label: "Track Width", value: "600 mm" },
      { label: "Min. Ground Clearance", value: "550 mm" },
      { label: "Max Digging Radius", value: "10950 mm" },
      { label: "Max Digging Depth", value: "7585 mm" },
      { label: "Hydraulic Pressure", value: "36 MPa" },
      { label: "Hydraulic Flow", value: "260 L/min (as shown)" },
      { label: "Bucket Digging Force", value: "204 kN" },
      { label: "Travel Speed", value: "3.3–5.7 km/h (as shown)" },
    ],
  },
  {
    id: "ht380-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht380-ht500.jpg"],
    name: { en: "HT380 Crawler Excavator" },
    short: { en: "38-ton class crawler excavator for heavy earthmoving and mining tasks." },
    points: { en: ["Large bucket capacity.", "Strong digging force.", "High productivity for project contractors."] },
    specPairs: [
      { label: "Engine Type", value: "6LTAA8.9-C325 II (239 kW/2200rpm)" },
      { label: "Overall Weight", value: "37200 kg" },
      { label: "Bucket Capacity", value: "2.0 m³" },
      { label: "Shipping Length", value: "11300 mm" },
      { label: "Transport Height", value: "3700 mm" },
      { label: "Overall Width", value: "3550 mm" },
      { label: "Track Length", value: "5045 mm" },
      { label: "Track Width", value: "600 mm" },
      { label: "Min. Ground Clearance", value: "471 mm" },
      { label: "Max Digging Radius", value: "10550 mm" },
      { label: "Max Digging Depth", value: "7370 mm" },
      { label: "Bucket Digging Force", value: "240 kN" },
      { label: "Travel Speed", value: "3.3–5.5 km/h" },
    ],
  },
  {
    id: "ht500-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-crawler-ht380-ht500.jpg"],
    name: { en: "HT500 Crawler Excavator" },
    short: { en: "50-ton class crawler excavator for heavy-duty mining and large construction sites." },
    points: { en: ["High hydraulic flow.", "Large bucket capacity.", "Strong digging and loading efficiency."] },
    specPairs: [
      { label: "Engine Type", value: "6LTAA8.9-C325 II (239 kW/2200rpm)" },
      { label: "Overall Weight", value: "49500 kg" },
      { label: "Bucket Capacity", value: "2.8 m³" },
      { label: "Shipping Length", value: "12150 mm" },
      { label: "Transport Height", value: "3550 mm" },
      { label: "Overall Width", value: "3580 mm" },
      { label: "Track Width", value: "600 mm" },
      { label: "Min. Ground Clearance", value: "740 mm" },
      { label: "Max Digging Radius", value: "10580 mm" },
      { label: "Max Digging Depth", value: "6260 mm" },
      { label: "Hydraulic Pressure", value: "37 MPa" },
      { label: "Hydraulic Flow", value: "400 L/min" },
      { label: "Bucket Digging Force", value: "276 kN" },
      { label: "Travel Speed", value: "3.0–4.8 km/h" },
    ],
  },
  {
    id: "ht75w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht75w-ht85wz.jpg"],
    name: { en: "HT75W Wheel Excavator" },
    short: { en: "Wheel excavator for urban jobsites with flexible mobility and fast relocation." },
    points: { en: ["Optional export engine shown.", "Suitable for municipal and road projects.", "Fast travel speed on road."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3065-T480 (48 kW/2200rpm); Optional YC4FA65-T300 (48 kW/2200rpm)" },
      { label: "Overall Weight", value: "7090 kg" },
      { label: "Bucket Capacity", value: "0.3 m³" },
      { label: "Shipping Length", value: "6200 mm" },
      { label: "Overall Width", value: "2180 mm" },
      { label: "Wheelbase", value: "2350 mm" },
      { label: "Boom Length", value: "3500 mm" },
      { label: "Max Digging Radius", value: "6385 mm" },
      { label: "Max Digging Depth", value: "3435 mm" },
      { label: "Bucket Digging Force", value: "45 kN" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht85wz-wheel-grab-loader",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht75w-ht85wz.jpg"],
    name: { en: "HT85W-Z Wheel Grab Loader" },
    short: { en: "Wheel grab loader for grabbing and handling materials with 360° rotatable gripper." },
    points: { en: ["Gripper opening up to 1250/1500 mm.", "Remote angle control 360°.", "Good for recycling/log handling yards."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3065-T480 (48 kW/2200rpm); Optional YC4FA65-T300 (48 kW/2200rpm)" },
      { label: "Overall Weight", value: "7400 kg" },
      { label: "Grab Weight", value: "1000 kg" },
      { label: "Shipping Length", value: "6600 mm" },
      { label: "Overall Width", value: "2180 mm" },
      { label: "Wheelbase", value: "2560 mm" },
      { label: "Boom / Stick", value: "3800 / 2000 mm" },
      { label: "Max Grabbing Height", value: "7540 mm" },
      { label: "Max Working Range", value: "7380 mm" },
      { label: "Max Opening Width", value: "1250/1500 mm" },
      { label: "Rotatable Angle", value: "360°" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht125w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht125w-ht145w.jpg"],
    name: { en: "HT125W Wheel Excavator" },
    short: { en: "Wheel excavator for city infrastructure and road maintenance with good reach." },
    points: { en: ["Export engine options shown.", "High travel speed.", "Dealer-friendly model for wide markets."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3085-T480 (62.5 kW/2200rpm); Optional YC4FA85-T300 (62.5 kW/2200rpm)" },
      { label: "Overall Weight", value: "9800 kg" },
      { label: "Bucket Capacity", value: "0.4 m³" },
      { label: "Shipping Length", value: "6600 mm" },
      { label: "Transport Height", value: "2900 mm" },
      { label: "Overall Width", value: "2540 mm" },
      { label: "Tail Turning Radius", value: "1890 mm" },
      { label: "Wheelbase", value: "2580 mm" },
      { label: "Max Digging Radius", value: "7000 mm" },
      { label: "Max Digging Depth", value: "3600 mm" },
      { label: "Bucket Digging Force", value: "58 kN" },
      { label: "Hydraulic Flow", value: "180 L/min" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht145w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht125w-ht145w.jpg"],
    name: { en: "HT145W Wheel Excavator" },
    short: { en: "14-ton wheel excavator for higher productivity and better loading performance." },
    points: { en: ["Higher digging capacity.", "Suitable for municipal contractors.", "Balanced specs for export." ] },
    specPairs: [
      { label: "Engine Type", value: "B3.9CS4 150C (110 kW/2500rpm) / QSB3.9-C125 (93 kW/2200rpm)" },
      { label: "Overall Weight", value: "13400 kg" },
      { label: "Bucket Capacity", value: "0.6 m³" },
      { label: "Shipping Length", value: "7900 mm" },
      { label: "Transport Height", value: "3255 mm" },
      { label: "Overall Width", value: "2580 mm" },
      { label: "Tail Turning Radius", value: "2395 mm" },
      { label: "Wheelbase", value: "2580 mm" },
      { label: "Boom Length", value: "4600 mm" },
      { label: "Stick Length", value: "2200 mm" },
      { label: "Max Digging Radius", value: "8060 mm" },
      { label: "Max Digging Depth", value: "4865 mm" },
      { label: "Bucket Digging Force", value: "85 kN" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht155w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht155w-ht185w.jpg"],
    name: { en: "HT155W Wheel Excavator" },
    short: { en: "Wheel excavator for roadworks and city projects with reliable powertrain." },
    points: { en: ["Engine options shown in spec.", "0.6m³ bucket capacity.", "High mobility on road."] },
    specPairs: [
      { label: "Engine Type", value: "B3.9CS4 150C (110 kW/2500rpm) / QSB3.9-C125 (93 kW/2200rpm)" },
      { label: "Overall Weight", value: "14500 kg" },
      { label: "Bucket Capacity", value: "0.6 m³" },
      { label: "Shipping Length", value: "7900 mm" },
      { label: "Transport Height", value: "3255 mm" },
      { label: "Overall Width", value: "2580 mm" },
      { label: "Track Width", value: "1900 mm" },
      { label: "Wheelbase", value: "2645 mm" },
      { label: "Boom / Stick", value: "4600 / 2200 mm" },
      { label: "Max Digging Height", value: "8720 mm" },
      { label: "Max Digging Depth", value: "4865 mm" },
      { label: "Max Unloading Height", value: "6300 mm" },
      { label: "Bucket Digging Force", value: "85 kN" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht185w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht155w-ht185w.jpg"],
    name: { en: "HT185W Wheel Excavator (Three-Section Boom)" },
    short: { en: "Three-section boom wheel excavator for extended reach and versatility." },
    points: { en: ["140 kW engine option shown.", "0.7m³ bucket capacity.", "Good for multi-scenario operations."] },
    specPairs: [
      { label: "Engine Type", value: "B5.9CS4 190C (140 kW/2200rpm) / 6BTA5.9-C180-II (132 kW/2200rpm)" },
      { label: "Overall Weight", value: "16100 kg" },
      { label: "Bucket Capacity", value: "0.7 m³" },
      { label: "Shipping Length", value: "8400 mm" },
      { label: "Transport Height", value: "3255 mm" },
      { label: "Overall Width", value: "2580 mm" },
      { label: "Wheelbase", value: "2645 mm" },
      { label: "Boom / Stick", value: "5100 / 2500 mm" },
      { label: "Max Digging Radius", value: "8550 mm" },
      { label: "Max Digging Height", value: "9022 mm" },
      { label: "Max Unloading Height", value: "6600 mm" },
      { label: "Bucket Digging Force", value: "92.2 kN (as shown)" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht190w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht190w-ht215w.jpg"],
    name: { en: "HT190W Wheel Excavator" },
    short: { en: "18-ton class wheel excavator for higher productivity in city and project work." },
    points: { en: ["Higher bucket capacity.", "Strong digging force.", "Good for contractors and rentals."] },
    specPairs: [
      { label: "Engine Type", value: "B5.9CS4 190C (140 kW/2200rpm) / 6BTA5.9-C180-II (132 kW/2200rpm)" },
      { label: "Overall Weight", value: "18800 kg" },
      { label: "Bucket Capacity", value: "1.0 m³" },
      { label: "Shipping Length", value: "9200 mm" },
      { label: "Transport Height", value: "3300 mm" },
      { label: "Overall Width", value: "2490 mm" },
      { label: "Wheelbase", value: "2850 mm" },
      { label: "Track Width", value: "1975 mm" },
      { label: "Boom / Stick", value: "5200 / 2600 mm" },
      { label: "Max Digging Radius", value: "9100 mm" },
      { label: "Max Digging Depth", value: "5700 mm" },
      { label: "Max Unloading Height", value: "6700 mm" },
      { label: "Bucket Digging Force", value: "142 kN" },
      { label: "Rotation Speed", value: "11 r/min (as shown)" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht215w-wheel-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-wheel-ht190w-ht215w.jpg"],
    name: { en: "HT215W Wheel Excavator" },
    short: { en: "21.5-ton class wheel excavator for high-efficiency operations." },
    points: { en: ["Larger boom and stick.", "Higher max unloading height.", "Good for project contractors."] },
    specPairs: [
      { label: "Engine Type", value: "B5.9CS4 190C (140 kW/2200rpm) / 6BTA5.9-C180-II (132 kW/2200rpm)" },
      { label: "Overall Weight", value: "21500 kg" },
      { label: "Bucket Capacity", value: "1.0 m³" },
      { label: "Shipping Length", value: "9700 mm" },
      { label: "Transport Height", value: "3500 mm" },
      { label: "Overall Width", value: "2490 mm" },
      { label: "Wheelbase", value: "2855 mm" },
      { label: "Track Width", value: "1975 mm" },
      { label: "Boom / Stick", value: "5700 / 2900 mm" },
      { label: "Hydraulic Tank Capacity", value: "215 L" },
      { label: "Fuel Tank Capacity", value: "350 L" },
      { label: "Max Digging Radius", value: "10050 mm" },
      { label: "Max Digging Depth", value: "6457 mm" },
      { label: "Max Unloading Height", value: "8020 mm" },
      { label: "Bucket Digging Force", value: "152.7 kN (as shown)" },
      { label: "Hydraulic Flow", value: "239 L/min (as shown)" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht115wg-wheel-grab-loader",
    category: "construction",
    images: ["assets/img/extracted/ht-grab-ht115wg-ht125wg.jpg"],
    name: { en: "HT115W-G Wheel Grab Loader" },
    short: { en: "Wheel grab loader for handling logs, scrap, and bulk materials." },
    points: { en: ["Lifting weight 1800 kg.", "Max opening width 1450 mm.", "5/1 gears mechanical shift."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3085-T480 (62.5 kW/2200rpm); Optional YC4FA85-T300 (62.5 kW/2200rpm)" },
      { label: "Overall Weight", value: "8680 kg" },
      { label: "Lifting Weight", value: "1800 kg" },
      { label: "Shipping Length", value: "6500 mm" },
      { label: "Overall Width", value: "2200 mm" },
      { label: "Wheelbase", value: "2580 mm" },
      { label: "Max Grabbing Height", value: "7630 mm" },
      { label: "Max Working Range", value: "7450 mm" },
      { label: "Max Opening Width", value: "1450 mm" },
      { label: "Rotatable Angle", value: "360°" },
      { label: "Shift Mode", value: "Mechanical 5 gears (manual)" },
      { label: "Gears (F/R)", value: "5/1" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht125wg-wheel-grab-loader",
    category: "construction",
    images: ["assets/img/extracted/ht-grab-ht115wg-ht125wg.jpg"],
    name: { en: "HT125W-G Wheel Grab Loader" },
    short: { en: "Upgraded wheel grab loader with higher lifting capacity and wider opening." },
    points: { en: ["Lifting weight 2000 kg.", "Max opening width 2000 mm.", "Dealer-friendly for recycling & forestry markets."] },
    specPairs: [
      { label: "Engine Type", value: "YCF3085-T480 (62.5 kW/2200rpm); Optional YC4FA85-T300 (62.5 kW/2200rpm)" },
      { label: "Overall Weight", value: "8700 kg" },
      { label: "Lifting Weight", value: "2000 kg" },
      { label: "Shipping Length", value: "6700 mm" },
      { label: "Overall Width", value: "2200 mm" },
      { label: "Wheelbase", value: "2580 mm" },
      { label: "Max Grabbing Height", value: "8100 mm" },
      { label: "Max Working Range", value: "7600 mm" },
      { label: "Max Opening Width", value: "2000 mm" },
      { label: "Rotatable Angle", value: "360°" },
      { label: "Shift Mode", value: "Mechanical 5 gears (manual)" },
      { label: "Gears (F/R)", value: "5/1" },
      { label: "Travel Speed", value: "30 km/h" },
    ],
  },
  {
    id: "ht150t-railway-crawler-excavator",
    category: "construction",
    images: ["assets/img/extracted/ht-rail-ht150t-ht100sf.jpg"],
    name: { en: "HT150-T Railway Crawler Excavator" },
    short: { en: "Railway crawler excavator with applicable track gauge for rail maintenance and construction." },
    points: { en: ["Applicable track gauge 1435/1520.", "Travel on rail wheels supported.", "Suitable for rail contractors."] },
    specPairs: [
      { label: "Engine Type", value: "QSB5.9-C180 (135 kW/2200rpm)" },
      { label: "Overall Weight", value: "15000 kg" },
      { label: "Applicable Track Gauge", value: "1435 / 1520 mm" },
      { label: "Shipping Length", value: "7650 mm" },
      { label: "Tail Turning Radius", value: "2400 mm" },
      { label: "Turntable Width", value: "2490 mm" },
      { label: "Track Width", value: "500 mm" },
      { label: "Max Digging Radius", value: "6300 mm" },
      { label: "Hydraulic Pressure", value: "32 MPa" },
      { label: "Hydraulic Flow", value: "212.6 L/min (as shown)" },
      { label: "Rail Wheel Max Speed", value: ">20 km/h (as shown)" },
    ],
  },
  {
    id: "ht100sf-railway-screening-machine",
    category: "construction",
    images: ["assets/img/extracted/ht-rail-ht150t-ht100sf.jpg"],
    name: { en: "HT100SF Railway Screening Machine" },
    short: { en: "Railway screening machine for ballast/sieve plate cleaning with conveyor system." },
    points: { en: ["Max excavation radius 5200 mm; depth 2200 mm.", "Conveyor belt swing 0–90°.", "Vibration frequency 25–30 Hz (as shown)."] },
    specPairs: [
      { label: "Engine Type", value: "YUCHAI YC4FA85-T300 (62.5 kW/2200rpm)" },
      { label: "Overall Weight", value: "8500 kg" },
      { label: "Bucket Capacity", value: "0.5 m³" },
      { label: "Transport Dimensions (L×W×H)", value: "6280×2828 mm (as shown)" },
      { label: "Wheelbase", value: "2600/4400 mm (as shown)" },
      { label: "Track Gauge", value: "1570 mm" },
      { label: "Track Width", value: "400 mm" },
      { label: "Min. Ground Clearance", value: "300 mm" },
      { label: "Max Excavation Radius", value: "5200 mm" },
      { label: "Max Excavation Depth", value: "2200 mm" },
      { label: "Max Excavation Force", value: "28 kN" },
      { label: "Conveyor Belt Swing Angle", value: "0–90°" },
      { label: "Vibration Frequency", value: "25–30 Hz" },
    ],
  },
  {
    id: "ht4cxwz-backhoe-loader",
    category: "construction",
    images: ["assets/img/extracted/ht-backhoe-awp-scissor.jpg"],
    name: { en: "HT4CX-WZ Backhoe Loader" },
    short: { en: "Backhoe loader for multi-purpose jobsite operations: digging, loading and material handling." },
    points: { en: ["75 kW power shown.", "Bucket capacity 1.2 m³; backhoe capacity 0.3 m³.", "Good for contractors and municipal projects."] },
    specPairs: [
      { label: "Engine Type", value: "YUCHAI YC4A105Z-T20" },
      { label: "Power", value: "75 kW / 2200 rpm" },
      { label: "Overall Weight", value: "10050 kg" },
      { label: "Bucket Capacity", value: "1.2 m³" },
      { label: "Backhoe Capacity", value: "0.3 m³" },
      { label: "Shipping Length", value: "6600 mm" },
      { label: "Transport Height", value: "3580 mm" },
      { label: "Overall Width", value: "2550 mm" },
      { label: "Track Width", value: "2150 mm" },
      { label: "Wheelbase", value: "2345 mm" },
      { label: "Max Digging Height", value: "5850/6590 mm (as shown)" },
      { label: "Max Digging Depth", value: "4270/5070 mm (as shown)" },
      { label: "Max Unloading Height", value: "4030/4840 mm (as shown)" },
    ],
  },
  {
    id: "ht-scissor-awp-series",
    category: "construction",
    images: ["assets/img/extracted/ht-backhoe-awp-scissor.jpg"],
    name: { en: "Scissor Aerial Work Platform (EV Series)" },
    short: { en: "Electric scissor lift series for warehouse and maintenance operations." },
    points: { en: ["Models: HT1214EV / HT1012EV / HT0608EV.", "Stable platform, indoor/outdoor usage (by spec).", "Suitable for distributors and rental companies."] },
    specPairs: [
      { label: "Models", value: "HT1214EV / HT1012EV / HT0608EV" },
      { label: "Working Height", value: "14 m / 12 m / 7.6 m" },
      { label: "Platform Height", value: "12 m / 10 m / 5.6 m" },
      { label: "Rated Load", value: "350 kg / 350 kg / 230 kg" },
      { label: "Overall Weight", value: "3100 kg / 3000 kg / 1250 kg" },
      { label: "Platform Extension", value: "0.9 m / 0.9 m / 0.6 m" },
      { label: "Battery", value: "4×6V/260Ah; 4×6V/260Ah; 2×12V/115Ah (as shown)" },
    ],
  },
  {
    id: "ht-curved-boom-awp",
    category: "construction",
    images: ["assets/img/extracted/ht-awp-boom.jpg"],
    name: { en: "Curved Boom Aerial Work Platform" },
    short: { en: "Curved boom aerial work platform for higher reach and flexible positioning." },
    points: { en: ["Max platform height 19.7 m.", "Max horizontal extension 11.8/10 m (as shown).", "Suitable for maintenance and industrial use."] },
    specPairs: [
      { label: "Maximum Platform Height", value: "19.7 m" },
      { label: "Maximum Horizontal Extension", value: "11.8 / 10 m (as shown)" },
      { label: "Overall Weight", value: "9200 kg" },
      { label: "Rated Load", value: "258 / 320 kg (as shown)" },
      { label: "Stowed Length", value: "9100 mm" },
      { label: "Stowed Width", value: "2500 mm" },
      { label: "Wheelbase", value: "2500 mm" },
      { label: "Max Gradeability", value: "45%" },
    ],
  },
  {
    id: "ht-straight-boom-awp",
    category: "construction",
    images: ["assets/img/extracted/ht-awp-boom.jpg"],
    name: { en: "Straight Boom Aerial Work Platform" },
    short: { en: "Straight boom aerial work platform for larger working range and height." },
    points: { en: ["Max platform height 22.5 m.", "Maximum working range 17 m.", "DEUTZ engine brand shown."] },
    specPairs: [
      { label: "Maximum Platform Height", value: "22.5 m" },
      { label: "Maximum Working Range", value: "17 m" },
      { label: "Overall Weight", value: "12300 kg" },
      { label: "Rated Load", value: "300 / 400 / 480 kg (as shown)" },
      { label: "Stowed Height", value: "2745 mm" },
      { label: "Wheelbase", value: "2500 mm" },
      { label: "Minimum Ground Clearance", value: "340 mm" },
      { label: "Engine Brand", value: "DEUTZ" },
      { label: "Fuel Tank Capacity", value: "160 L" },
    ],
  },

  {
    id: "wheel-loader-3t",
    category: "construction",
    images: ["assets/img/extracted/hero-bg.png"],
    name: {
      en: "Wheel Loader (3 Ton Class)",
      fr: "Chargeuse sur pneus (3 tonnes)",
      es: "Cargadora de ruedas (3 toneladas)",
      ar: "لودر بعجلات (فئة 3 طن)",
      ru: "Фронтальный погрузчик (3 т)",
      pt: "Pá carregadeira (3 toneladas)",
    },
    short: {
      en: "For contractors and rental companies: reliable configuration with spare parts support.",
      fr: "Pour entrepreneurs et location : configuration fiable et support pièces.",
      es: "Para contratistas y alquiler: configuración confiable y repuestos.",
      ar: "للمقاولين والتأجير: مواصفات موثوقة ودعم قطع الغيار.",
      ru: "Для подрядчиков и аренды: надёжная комплектация и запчасти.",
      pt: "Para empreiteiras e locadoras: configuração confiável e peças.",
    },
    points: {
      en: ["Factory-selected configuration for stable lead time.", "Support OEM spare parts list for maintenance.", "Suitable for Africa / South America / Central Asia projects."],
      fr: ["Configuration sélectionnée pour délais stables.", "Liste pièces OEM pour maintenance.", "Adapté aux projets Afrique / Amérique du Sud / Asie centrale."],
      es: ["Configuración seleccionada para plazo estable.", "Lista de repuestos OEM.", "Adecuado para proyectos en África/LatAm/Asia Central."],
      ar: ["تجهيزات مختارة لضمان وقت تسليم مستقر.", "قائمة قطع غيار OEM للصيانة.", "مناسب لمشاريع أفريقيا وأمريكا الجنوبية وآسيا الوسطى."],
      ru: ["Подбор комплектации для стабильных сроков.", "Поддержка списка OEM-запчастей.", "Подходит для проектов в Африке/ЛатАме/Центр. Азии."],
      pt: ["Configuração selecionada para prazo estável.", "Lista de peças OEM para manutenção.", "Adequado para projetos na África/América do Sul/Ásia Central."],
    },
    specs: {
      modelRange: "3T class (custom)",
      dimensions: "By model",
      enginePower: "By model",
      pto: "N/A",
      frontTread: "N/A",
      rearTread: "N/A",
      traction: "N/A",
      minWeight: "By model",
      transmission: "Power shift (typical)",
      steering: "Hydraulic articulation",
      warranty: "12 months",
      notes: "Replace placeholders with your selected model spec sheet.",
    },
  },

  {
    id: "oem-spare-parts",
    category: "spare_parts",
    images: ["assets/img/extracted/factory-1.png"],
    name: {
      en: "Machinery Spare Parts (OEM Supply)",
      fr: "Pièces détachées (OEM)",
      es: "Repuestos (OEM)",
      ar: "قطع غيار (OEM)",
      ru: "Запчасти (OEM)",
      pt: "Peças de reposição (OEM)",
    },
    short: {
      en: "Original spare parts and wear parts for tractors, implements and construction equipment.",
      fr: "Pièces d’origine et pièces d’usure pour tracteurs et engins.",
      es: "Piezas originales y de desgaste para tractores y maquinaria.",
      ar: "قطع أصلية وقطع استهلاكية للجرارات والمعدات.",
      ru: "Оригинальные и расходные запчасти для техники.",
      pt: "Peças originais e de desgaste para máquinas.",
    },
    points: {
      en: ["Support part number matching based on photos/specs.", "Packaging and labeling for distributors.", "Consolidated shipment with machines to save cost."],
      fr: ["Correspondance références via photos/spécifications.", "Emballage/étiquetage pour distributeurs.", "Expédition groupée pour réduire le coût."],
      es: ["Coincidencia de número de parte por fotos/especificaciones.", "Empaque y etiquetado para distribuidores.", "Envío consolidado para ahorrar costos."],
      ar: ["مطابقة أرقام القطع حسب الصور/المواصفات.", "تغليف وملصقات للموزعين.", "شحنات مجمعة لتقليل التكلفة."],
      ru: ["Подбор артикулов по фото/характеристикам.", "Упаковка и маркировка для дистрибьюторов.", "Консолидация отгрузок для экономии."],
      pt: ["Correspondência de códigos por fotos/especificações.", "Embalagem e rotulagem para distribuidores.", "Envio consolidado para reduzir custos."],
    },
    specs: {
      modelRange: "Tractors / Implements / Construction Equipment",
      dimensions: "N/A",
      enginePower: "N/A",
      pto: "N/A",
      frontTread: "N/A",
      rearTread: "N/A",
      traction: "N/A",
      minWeight: "N/A",
      transmission: "N/A",
      steering: "N/A",
      warranty: "As per part type",
      notes: "Send us your part list or machine model, we will confirm availability and lead time.",
    },
  },
];
